apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-web
  namespace: egi-inventario
  labels:
    app: inventario-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-web
  template:
    metadata:
      labels:
        app: inventario-web
    spec:
      containers:
        - name: inventario-web
          image: inventario-itu:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_HOST
              value: "inventario-db"
            - name: MYSQL_HOST
              value: "ubicacion-db"
            - name: LDAP_URL
              value: "ldap://ldap-service:389"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
