apiVersion: v1
kind: Service
metadata:
  name: inventario-web
  namespace: egi-inventario
  labels:
    app: inventario-web
spec:
  type: NodePort
  selector:
    app: inventario-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
