apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: egi-inventario
type: Opaque
# Valores en base64:
#   echo -n "admin" | base64        → YWRtaW4=
#   echo -n "admin1234" | base64    → YWRtaW4xMjM0
#   echo -n "inventario_hardware" | base64 → aW52ZW50YXJpb19oYXJkd2FyZQ==
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM0
  database: aW52ZW50YXJpb19oYXJkd2FyZQ==
