apiVersion: v1
kind: Service
metadata:
  name: inventario-db
  namespace: egi-inventario
  labels:
    app: inventario-db
spec:
  selector:
    app: inventario-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
